### ISSUE TITLE
意外发现自己翻译的文章在这里

### ISSUE THREAD

**Issue by qinxiandiqi** [AvatarQing/Gradle-Plugin-User-Guide-Chinese-Verision#7]
虽然Google没有明确授权给我翻译，Google保留翻译权，所以我所翻译的东西我也没有什么版权，不能追究什么。万一哪天Google想要追求我侵权，我还得承担一定责任，虽然Google一般不会跟我这种小屁民计较这种事情。自己当初选择去翻译这些文章也是为了方便大家学习，很感激你为我的翻译做了一些校对以及生成更方便使用的gitbook，并且也采用了开源协议，没有私自享用，我也没什么好说的。但是在完全没有任何通知的情况下就使用我的翻译，等到自己搜Google才意外发现有这回事，心里感觉还是挺不好受的。希望以后你在使用别人的翻译时，能提前通知一下译者，征得同意，毕竟翻译这么长的文章也不是件容易的事情，互相尊重一下大家的劳动成果。:)

**Comment by AvatarQing** [comment]
实在是抱歉了，当初转载时没有考虑太多，以后再转载其他作品一定征得原作者同意。

**Comment by qinxiandiqi** [comment]
:)
